import styled from 'styled-components'

export const SongListContainer = styled.div`
    .songlist_top_bar{
        position:fixed;
        top:0;
        z-index:5;
        width:100%;
        height:.5rem;
        background:#15171f;
        color:#fff;
        div{
            line-height:.5rem;
            span{
                margin-left:.15rem;
                font-size:.16rem;
            }
        }   
    }
    .songlist_banner{
        width:100%;
        background:#15171f;
        .banner-box{
            display:flex;
            align-items:center;
            width:100%;
            height:1.3rem;
            .pic_box{
                width:1rem;
                height:1rem;
                margin-left:.2rem;
                position:relative;
                img{
                    width:100%;
                    height:100%;
                    vertical-align:middle;
                }
                div{
                    position:absolute;
                    top:0;
                    right:.02rem;
                    .iconfont{
                        color:#fff;
                        font-size:.08rem;
                    }
                    .playcount{
                        color:#fff;
                        font-size:.08rem;
                    }
                }
            }
            .summary-box{
                padding:0 .1rem;
                box-sizing:border-box;
                width:2rem;
                h1{
                    color:#fff;
                    font-weight:bold;
                    font-size:.16rem;
                }
                p{
                    height:.4rem;
                    line-height:.4rem;
                    display:flex;
                    align-items:center;
                    img{
                        width:.2rem;
                        border-radius:50%;
                        vertical-align:middle;
                    }
                    span{
                        display:block;
                        font-size:.12rem;
                        padding:0 .05rem;
                        color:#ccccce;
                        width:auto;
                    }
                    .iconfont{
                        display:block;
                        color:66686d;
                        font-style:normal;
                        font-size:.12rem;
                    }
                }
            }
        }
        p{
            display:flex;
            height:.4rem;
            padding-bottom:.2rem;
            span{
                display:flex;
                flex-direction:column;
                justify-content:space-around;
                align-items:center;
                width:25%;
                height:100%;
                color:#fff;
                .iconfont{
                    font-size:.16rem;
                }
                em{
                    font-size:.14rem;
                    font-weight:normal;
                }
            }
        }
    }
    .fn{
        width:100%;
        height:.4rem;
        margin-top:-.1rem;
        display:flex;
        justify-content:space-between;
        border-bottom:1px solid #ccc;
        border-radius:.08rem .08rem 0 0;
        background:#fff;
        .collect{
            width:30%;
            border-radius:0 .08rem 0 0;
            background:#ea4a3e;
            color:#fff;
            display:flex;
            justify-content:center;
        }
        p{
            width:30%;
            display:flex;
            align-items:center;
            .iconfont{
                margin:0 .1rem;
                font-size:.14rem;
            }
            .play_all{
                font-weight:bold;
                font-size:.14rem;
            }
            .select_more{
                font-weight:bold;
                font-size:.12rem;
            }
        }
    }
    ul{
        li{
            display:flex;
            overflow:hidden;
            .album{
                display:flex;
                justify-content:center;
                align-items:center;
                width:15%;
                margin:.1rem 0;
                color:#afafaf
                
                img{
                    width:.4rem;
                    height:.4rem;
                    border-radius:.03rem;
                }
            }
            .song_list{
                display:flex;
                width:85%;
                justify-content:space-between;
                border-bottom:1px solid #ccc;
                .song_details{
                    display:flex;
                    flex-direction:column;
                    justify-content:space-around;
                    .song_summary{
                        .song_name{
                            font-size:.1rem;
                            font-weight:bold;
                        }
                        .song_alias{
                            font-size:.1rem;
                            font-weight:normal;
                            color:#999999;
                        }
                    }
                    .song_artists{
                        font-size:.06rem;
                    }
                }
                .song_play{
                    display:flex;
                    justify-content:center;
                    align-items:center;
                    .iconfont{
                        margin-right:.2rem;
                        font-size:.14rem
                    }
                }
            }
        }
    }

`